### ISSUE TITLE
Ever considered making 'feature' synonymous with 'feat'?

### ISSUE THREAD

**Issue by johnslemmer** [conventional-commits/conventionalcommits.org#106]
There is a lot wisdom in coding that variable names etc shoudn't be shortened or abbreviated.  It makes code more readable.  And we all know code is read a lot more than it is written.

So, with that in mind have you thought about making it acceptable to write `feature` instead of just `feat`? (I would love to see `feat` dissapear but too much time has passed and there is too much history and tooling dependent on this that a breaking change like this wouldn't be possible).  Right now the spec is very strict when it comes to this, and I was hoping that `feature` could be added to the spec.

Every other "commit type" is a fully written out word (except `perf` I guess, but the non-spec types don't really matter as much because it just depends on the tooling a project used).  Anyway, it seems reasonable to allow people to follow that pattern.

Lastly, on a personal note, I just started using [standard-version](https://github.com/conventional-changelog/standard-version) to help maintain my personal projects, and found that I kept writing `feature: some new feature was added` in commit statements because I'm pretty anal about writing out words for readability.  Obviously this isn't a big deal, and I just edited all of my past incorrect commit statements.  But it seems to me that `feature` is a reasonable word to add to the spec.

Thanks for coming up with this spec, and allowing it to drive some wonderful tooling!!

**Comment by stevemao** [comment]
Just in general I try to avoid too many options because of [tragedy of the commons](https://en.wikipedia.org/wiki/Tragedy_of_the_commons). And also this spec is supposed to be strict.

**Comment by johnslemmer** [comment]
Makes sense. Thanks for thinking about it.

**Comment by rbwhitaker** [comment]
Well I'm late to the party, but I have to agree. I think "feature" is far better. So many code style guides require that you spell out the words rather than arbitrarily shortening them. I'd rather "feature" be the choice here, not "feat." (Though I'd also get behind both options.)

I love what you've got going on here. I think this is a thing our company has been needing. But the "feet" [sic] thing bugs me enough to make me seriously consider just coming up with our own convention. I'm going to bring up Conventional Commits to the other leads here and see what they think. It might not bother them as much and we might just roll with it as it is.

But I do want to make you(@stevemao) aware of the fact that this isn't just one person with a personal preference. It's a larger group of at least two. ("There are dozens of us!")

I get the tragedy of the commons thing; I think it is a good rule of thumb to keep it simple. But this might be a reasonable exception to that.
