### ISSUE TITLE
type annotation / header file / declaration file

### ISSUE THREAD

**Issue by Mouvedia** [conventional-commits/conventionalcommits.org#114]
What's the proper type for a d.ts file* update?
What about JSDoc comments?

I think it's refactor but docs might be correct too.

<sub>\* TypeScript declaration file</sub>

**Comment by stevemao** [comment]
I'd use refactor in this case

**Comment by bcoe** [comment]
@stevemao thanks for fielding this. @Mouvedia sounds like you both lean towards `refactor`, I'd run with this 👍 


Keep in mind that the spec doesn't strictly define most `types`, so it's more important that you're consistent in your own project, and document the approach used, rather than always come to 100% agreement on type name with folks outside your project.
