### ISSUE TITLE
docker node-sass issue

### ISSUE THREAD

**Issue by seognil** [conventional-commits/conventionalcommits.org#125]
To me, it's always unable to build css while local dev.
while up docker and browse `http://localhost:1313`
css file missing

But I finally found a way after try everything
 
```
cd themes/conventional-commits
npm install --save-dev node-sass
npm install
npm run build
cd ../../
```
and then run the `docker-compose up` as README said
It just worked at least
(I didn't add these changes in my latest Chinese text PR)

---

The error info I saw was:
```
Downloading binary from https://github.com/sass/...blahblah.../v4.9.3/...blahblah...
Cannot download "https://github.com/sass/...blahblah.../v4.9.3/...blahblah..."
HTTP error 404 Not Found
```
But it goes well after I do the npm update staff

Haven't figure out why yet
I'm in China and using Mac (maybe network issue? but really couldn't find the release when I manually check the node-sass Github repo)

---

Maybe it's necessary to update the deps

Or only add my case to README (if only few guys meet this issue)
(also unable to use yarn at first, haven't try that after npm worked)

**Comment by damianopetrungaro** [comment]
I will take a look this week, ping me back if I won't reply 👍 
Nice spot :D

**Comment by MSakamaki** [comment]
I also have this problem and found a solution.

The cause is `sass:watch` in npm-sctiprs of the theme.
If you build after creating content, css is not generated because scss does not change.

There are two ways to solve this:

1. After building scss once, include in commit `themes/conventional-commits/static/css/style.css`
2. add normal scss-build-tasks as  npm start.

If determine which is best, I will to make a PR.

**Comment by damianopetrungaro** [comment]
@MSakamaki this one seems reasonable `add normal scss-build-tasks as npm start.`.

Do you want to do it? I can assign you on this!

**Comment by MSakamaki** [comment]
@damianopetrungaro 
Yes, leave it to me.
I will make a PR.
