### ISSUE TITLE
Should `fix` for the new feature in current version use `fix` or ... ?

### ISSUE THREAD

**Issue by mineschan** [conventional-commits/conventionalcommits.org#186]
Hi guys, me and our team are trying to adopt this convention into our projects. And I come to this confusion and hope someone can give me some advises.

During an on-going sprint, new feature created and push to our repo with `feat`, which totally make sense and it will be included when we use tool to generate CHANGELOG. But then QA found a bug and ask developer the fix it right away. 

So the develop would fix it and push to repo with `fix`, what bothering me is that, it would also be included when we generate the CHANGELOG afterwards, which make no sense.

What should we use for this kind of bug fixing? Appreciated for any suggestions.

**Comment by damianopetrungaro** [comment]
I think the right way is to rebase and squash the fix into the feature so that the PR has just 1 commit with the working feature.

If the `feat` has already been merged into the master, then you have no option rather than push a `fix` :D 

Let me know if this makes send and reply to your doubt 😄

**Comment by wesleytodd** [comment]
> If the feat has already been merged into the master, then you have no option rather than push a fix :D

Technically you can still rebase, fix, and force push.  It depends on your team and how comfortable they all are with rebasing on top of a changed remote branch.  I personally do this quite often, but it does require any teammates to know what to do, so it is probably best avoided by other git hygiene practices (like qa'ing on a feature or release branch).

**Comment by damianopetrungaro** [comment]
@wesleytodd force pushing sounds like "yolo, all the other ppl will need to rebase before merging their PR", I'd not love it tho 😂 
Also IMHO if has been written in the main (aka master) then I'd love to keep it like that since it show a clear historical reason about when a bug was introduced/deployed/reverted/fixed (or similar).

@mineschan I'm gonna close this one, if you have any other question regarding this, feel free to reopen it! :D

**Comment by wesleytodd** [comment]
Yep, just depends on the project and team.  I rebase basically every PR (if I am the author or merger) anyway, so doesn't matter much to me.  Still, I agree usually you would want to avoid it, and there is no reason *not* to push the following `fix` commit.  

Agreed closing is the best for this since it is pretty well sorted out and isn't really a change to the spec.
