### ISSUE TITLE
Add recommended type "ui"

### ISSUE THREAD

**Issue by Zerotask** [conventional-commits/conventionalcommits.org#281]
In the current definition I'm missing a type for UI related changes, e. g. changed the color of a button.

There is a style type, but that is rather meant for coding styles
> style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)

(From Angular's convention)

I'm aware that you can define your own types and they're just suggestions ("commit types other than fix: and feat: are allowed, for example (...)"), but for me and for many projects **UI** is something fundamental and therefore I recommend to mention `ui` in the definition.

Example:
`ui(contact-page): changed the color of the send button`

**Comment by SirWindfield** [comment]
The specification is not here to define every single possible type. The mandatory types to make semantic versioning work are defined as `feat` and `fix`. This, alongside of the definition of breaking changes, allows people to create consistently versioned projects.

The rest is kind of irrelevant. You can define your own types, heck, you can even use emojis for them. Conventional commits just defines the needed baseline, you can define the rest.

Mentioning `ui` doesn't add any value. There are already other resources at the bottom of the page, even to the angular commit styleguide. Which is a good reference IMO.

**Comment by Zerotask** [comment]
I just suggested one additional type, not _every single possible type_. Also I know the mandatory types and as I said I'm also aware that I can define my own types.

As I already stated above, many projects have UI elements and therefore it would be a good addition to add it as a **recommended type** (NOT a mandatory type). This would add value. It would add a more specific and informative description of the commit and it wouldn't lead to breanking changes.

If you don't need a **ui** type then simply ignore my suggestion instead of creating a destructive post. Thanks.

**Comment by SirWindfield** [comment]
My post is in no way destructive, I just pointed out my own opinion. Conventional commits are also used for applications that do not have any UI whatsoever. However, the other types that are recommended fit into every kind of project. UI is too specific IMO. You are free to add anything to your own projects as a type, but I think that those given as an example should fit every project. And `ui` definitely doesn't.

A specification and its related documents should be as generic as possible.

**Comment by Zerotask** [comment]
For me it sounds destructive as your post doesn't add any value to this suggestion. This isn't meant to be unfriendly, this is just how I declare it, objectively. If you feel offended by me, I'm sorry. This was not my intention.

Personally if I don't like a suggestion, I simply ignore it (if I'm not a member of the project) and if I strongly disagree with it, I simply put a thumb down.


> but I think that those given as an example should fit every project

There are many projects out there which don't have a CI/CD pipeline (`ci`), documentation (`docs`) or tests (`test`).
But that doesn't mean that those types are not generic. Same goes for UI, which is a generic topic in software development, even if not every project has an UI.
I mean this suggestion is just to add a few letters, no breaking changes etc. I think there is no need to start a bigger discussion about it. ;)

**Comment by damianopetrungaro** [comment]
@Zerotask I don't see the value of adding it, probably you're looking at the specs from the wrong point of view.

Let's say you change the color of a button, but how applying that commit is going to affect the codebase?
Is it gonna add a new feature because blue is better than red? Is it gonna fix an issue because the hex used was the wrong one?

Alos, "ui" is too close to a specific kind of development, for example, HTTP servers don't have at all the concept of UI.

**Comment by SirWindfield** [comment]
@damianopetrungaro 
I think we argued the same in the last paragraph, you phrased it better than me though! :)

**Comment by damianopetrungaro** [comment]
Since we are arguing I'd say it's not objective 
> I think I have an objective point of view to that.

The reason why CC was created is because of deployment automation and reasonable benefit understanding the impact of each commit within the whole git history, this leads to the reason why fea/fix and BC are the only "official" naming and all the others are optional.

Also, let me help you to reinterpret your last point:

> 
> That's a good point.
> The current specification says
> 
>     Types other than feat and fix MAY be used in your commit messages.
> 
> The referenced RFC 2119 says about MAY:
> 
>     MAY This word, or the adjective "OPTIONAL", mean that an item is
>     truly optional. One vendor may choose to include the item because a
>     particular marketplace requires it or because the vendor feels that
>     it enhances the product while another vendor may omit the same item.
> 

This means that nothing is blocking you to create your own custom type that fits your personal/company usage, but on the other hand, this flexibility doesn't need to be """imposed for all the clients""" and should still be as applicable as possible regarding the context.

Since the `ui` type is not usable in all the scenario by its design (reason to exist), probably will be ending up with pollution of suggested types that are not usable in all the scenarios.


I am always open to discuss, there isn't only my voice but the voice of the community :D
If more folks/companies will see value in this we may add it, or specify it somehow on the website.
