### ISSUE TITLE
Can Sourcetree support this convention?

### ISSUE THREAD

**Issue by liaokaime** [conventional-commits/conventionalcommits.org#320]
I want to install plug-ins on Sourcetree to support this convention. But I searched Google and found nothing. Do you know anything about it. Sourcetree is a so great tool for me.

**Comment by damianopetrungaro** [comment]
Hey @liaokaime ! I have never used Sourcetree but since it is based on git as a version-control system, I do not see why it should not support it tho!

It's on you probably to write the commit messages in the right way, if the tool you're using supports plugins you may try to look if there's one that may help you to automate the process :D

**Comment by damianopetrungaro** [comment]
Gonna close, let me know if you have any other question and we can reopen the issue 💪

**Comment by liaokaime** [comment]
thanks

**Comment by damianopetrungaro** [comment]
@liaokaime Take a look here:
https://dzone.com/articles/using-conventional-commit-in-project SourceTree is mentioned!
