### ISSUE TITLE
Modify format of conventional commits

### ISSUE THREAD

**Issue by topolanekmartin** [conventional-commits/conventionalcommits.org#455]
Hello,

I would like to change format of conventional commits in order to prepend task ID (in my case it would be Jira task id) to commit. You can see below new format:

`<[XXX-1234]> <type>[optional scope]: <description>`

Is it possible to modify it somehow? I mean some local file in which I would define new format for custom project. 

Thanks in advance for answer.

**Comment by Conaclos** [comment]
I could rather favor something like: `<type>[scope][!]: <desc> [ticket-ref]`

```
refactor(service): description (JIRA-1253)
```

This format (ticket in parens and after the description) seems widely used.

**Comment by dsbert** [comment]
> 

We do the same, and unfortunately it still breaks the spec (first line should be all lower-case).

**Comment by pip25** [comment]
The absence of task/ticket identifiers in the first commit line is the number one reason we cannot adopt this spec, and is honestly a surprising oversight. In many corporate environments, especially where the large number of developers makes the quality of commit messages rather uneven, a ticket ID **is** in fact the most essential information in the commit message. Relegating it to a footer entry, as the current examples show, hides a crucial detail from many commit history views, including Github's.

I think a place already exists in the current format that matches the role of a ticket ID well: the scope identifier. Instead of allowing only a single noun, I would suggest relaxing the requirements here to allow commit comments such as this:
```
fix(JIRA-1234): Fixed NullPointerException in SomeService
```
Or this:
```
refactor(#321): Removed unnecessary iterators
```

We could still disallow spaces in the scope field to discourage people from writing something overly long.

**Comment by bcoe** [comment]
People can update the message to have a suffix which represents a ticket #, like:

`refactor(service): description (JIRA-1253)`

As @Conaclos suggests.

Alternatively, we use git trailers to reference the originating ticket:

```
test: use fully qualified request type name in tests

Origin-RevId: 132334
```

With regards to @pip25's suggestion, I think this is reasonable for someone's internal use 👍, I could imagine us documenting this in the help section, as a potential option for people.

---

@topolanekmartin you can create your own custom parser you use internally at your company, that handles commits in the format you've suggested.

This repository describes a specification, and is not a tool for parsing commits.

For the specification itself, we are not going to introduce an additional prefix like `<[XXX-1234]>` ahead of the `type`, as I I think this is sufficiently supported by conventions like git trailers, or adding a suffix to the `description`.
