### ISSUE TITLE
Is there an abbr for `improvement`?

### ISSUE THREAD

**Issue by htchaan** [conventional-commits/conventionalcommits.org#66]
Since `improvement`(11 chars) is even longer than `feature` (7 chars), which is shortened as `feat`.

**Comment by damianopetrungaro** [comment]
Hey @htchaan thank you for the question!

I think it's quite long too, but at the moment there's no abbreviation for `improvement`, if you have a good idea feel free to suggest and discuss here in the issue!

Good ideas are always welcome 😄

**Comment by pmackay** [comment]
Would `improve` be an improvement on `improvement`? ;)

**Comment by htchaan** [comment]
I vote for `impr`. Its 4-char just like many other abbreviations eg.
`elem`, `feat`, `impl`.


Damiano Petrungaro <notifications@github.com> 於 2018年7月19日週四 上午12:49寫道：

**Comment by damianopetrungaro** [comment]
@hbetts  @stevemao @bcoe  wdyt about it?

**Comment by hbetts** [comment]
I didn't realize we recommended `improvement`.

> We also recommend improvement for commits that improve a current implementation without adding a new feature or fixing a bug

Honestly, if it's a code change, then the only non-feature, non-bug, _improvement_ would be a performance one, and for that you could use the Angular convention of `perf`.

Basically, I'm taking a step back and asking, do we even need _improvement_? What does it communicate that _feat_, _fix_, and _perf_, do not?

**Comment by pmackay** [comment]
>Basically, I'm taking a step back and asking, do we even need improvement? What does it communicate that feat, fix, and perf, do not?

What would a refactoring for code cleanup fit under?

**Comment by damianopetrungaro** [comment]
Hey!
Sorry but I had a weekend without internet 😄 

@hbetts  i suggested some months ago to introduce `improvement`, because `refactor` means it _MUST NOT_ introduce any breaking changes.

Instead `improvement` it's ok with API changes but does not introduce any external BC.

I am totally open to rediscuss it!

**Comment by hbetts** [comment]
> because refactor means it MUST NOT introduce any breaking changes.

I think I've used `refactor` in the past for breaking changes.

For example, I will _deprecate_ a function as part of a `patch`, but I won't remove it.

Then, at a later time, I will remove that function in a `refactor`, with a `BREAKING CHANGE` comment at the bottom of my commit message, explaining the removal, and the recommended migration path. I use `refactor` because I'm not adding a feature, and I don't consider removing a deprecated function as a bug `fix`.

I'm sorry if I'm derailing this issue. If y'all would like my thoughts on `improvement`, or additional personal examples, please let me know where I can post them.

---

As for abbreviation, yes, I would be fine with the recommendations. In particular, `impr`, because I kind of agree with @damianopetrungaro  about the other being more of a `verb`.

Any way to quantify the common abbreviated form of `improvement` as used by English language writers?

**Comment by damianopetrungaro** [comment]
@hbetts I'm totally fine about talking about it, our mission is to make the specs as better as possible 😄 

As you can see I do not agree with the usage of `refactor` with a `BREAKING CHANGE:` into it, it's a contradiction imho 😄 

___

Looking forward to any English native speaker about it 
>Any way to quantify the common abbreviated form of improvement as used by English language writers?

**Comment by hbetts** [comment]
I've spun off a discussion about `improvement` into #78 

As for this issue, I don't have the time to research whether `impr` is the common abbreviation of `improvement`.

Does anyone else have time?

**Comment by damianopetrungaro** [comment]
@hbetts I can take a look tomorrow ;)

**Comment by damianopetrungaro** [comment]
So after a little research, I found out we may use [IMPROV](https://www.acronymfinder.com/Improvement-(IMPROV).html) or [IMP](https://en.wiktionary.org/wiki/imp.)

**Comment by Mouvedia** [comment]
https://en.wikipedia.org/wiki/Imp

**Comment by bcoe** [comment]
👋 any objection to closing this pull request, I think the spec appropriately calls out the fact that folks can pick and choose their own types.

**Comment by Mouvedia** [comment]
I think we should close this one and reopen #78

**Comment by stevemao** [comment]
Closing now. Feel free to comment.

**Comment by batara666** [comment]
wait, so are we using imp: ?
