### ISSUE TITLE
Criteria For Migrating conventional-changelog Projects

### ISSUE THREAD

**Issue by hbetts** [conventional-commits/conventionalcommits.org#74]
What are the criteria for migrating [`conventional-changelog` projects](https://github.com/conventional-changelog) to the new organization?

**Comment by damianopetrungaro** [comment]
I think that there are no breaking changes after this rename because all the services that are using the linked repository will be redirected to the new one.

But anyway we should update the reference of the repository 😄  

- [ ] Update Heroku settings for CD 
- [ ] New logo
- [ ] Look for repositories to add to the organization

@hbetts  feel free to add more of them, and @bcoe and @stevemao  you may have more info because he was the main owner for a while 😄

**Comment by damianopetrungaro** [comment]
@bcoe  you are the only owner on the Heroku app, you should edit it 😛

**Comment by hbetts** [comment]
> Look for repositories to add to the organization

@damianopetrungaro I was actually looking for an answer to whether `conventional-changelog` is a good candidate to move into this org? How do I know it's a good candidate for this org? Who needs to approve the repository to be moved into this org?

**Comment by hbetts** [comment]
Sounds good @damianopetrungaro.

If we need to define this better, let's move it to our `meta` project.
