### ISSUE TITLE
Consolidate Summary Items With Specification

### ISSUE THREAD

**Issue by hutson** [conventional-commits/conventionalcommits.org#80]
I would like to suggest we consolidate the numbered items under the _Summary_ section into the _Conventional Commits Specification_ section.

**Comment by damianopetrungaro** [comment]
@hbetts what do you mean with this?

**Comment by hbetts** [comment]
Items 1 through 4 in the _Summary_ are a duplication of content in the _Specification_ section.

They feel like extra reading without adding any value.

**Comment by damianopetrungaro** [comment]
Let looks good to me, they are a summary of the specs.
What do you suggest?

**Comment by damianopetrungaro** [comment]
@hutson any other input?

**Comment by hutson** [comment]
Thank you for bringing it back to my attention.

So re-reading the website, I still feel the summary section is a duplicate of the specification content.

Now, perhaps, the summary can help learn the bare minimum needed to start using the convention. However, there are additional requirements in the specification that aren't covered in the summary. For example, the description is a requirement, yet it's not covered in the summary.

**Comment by damianopetrungaro** [comment]
I do agree with you, and there was a huge discussion with @bcoe  where me and him had different opinions.

This issue is the third time that someone has this feeling about it, so there is space for improvement.

Do you want to take it and try to rephrase it in a better way?

**Comment by bcoe** [comment]
Here's why I would strongly argue against removing the summary section. 

The motivation of standard-version, and the conventional-commits specification was that at npm, Inc, we were not doing a good job of documenting changes to npm's various services, such that whenever it came time to cut a release of npm Enterprise it was hard to tell what major features had changed since we last put the product out -- resulting in frequently breaking customers.

@nexdrew advocated pulling in a conventional commit message format, as a way to prevent this ... here's the problem, it's a pain in the butt to switch how your write commit messages, and getting buy-in from the engineering team would have potentially been difficult...

The goal was to create a convention and methodology so simple that engineers would gradually adopt it because it's a no brainer. Long story short, I'll argue that the summary is the most important part of this document, it's what demonstrates to engineers that you can start using the conventional commits methodology with a few simple changes to your engineering practices ... making someone read an 11-point specification does not do this.

**Comment by bcoe** [comment]
I might add that conventional-commits has been successful, and has gained wide adoption at npm, Inc and across other open-source projects, I think it would be a huge mistake to remove the simple summary of the specification in favor of the daunting 11-point specification.

**Comment by bcoe** [comment]
@hutson @damianopetrungaro 

> Now, perhaps, the summary can help learn the bare minimum needed to start using the convention. However, there are additional requirements in the specification that aren't covered in the summary.

☝️ this is exactly what the summary should be treated as, someone to hit the ground running with conventional commit messages, as an example, probably doesn't need to know:

_A footer MAY be provided one blank line after the body. The footer SHOULD contain additional issue references about the code changes (such as the issues it fixes, e.g.,Fixes #13)._

And it starts to feel a bit overwhelming if it feels like I _do_ need to know all these edge-cases. Perhaps  we just need to word-smith the summary a bit, so that it gets at the heart of the specification. 

... If folks do feel that we need all 11 points to hit the ground running with the spec, I'd argue that it's time to start over again with this project; we didn't succeed in making a simple convention.

**Comment by nexdrew** [comment]
My opinion might not hold a lot of weight, but I agree with @bcoe. Ever since adopting the convention - at npm, in my open source work, and with my current development team - the thing that has won people over is the simplicity of the convention and the ease of applying it to a [GitHub-flow](https://guides.github.com/introduction/flow/) methodology.

I, for one, appreciate the simplified summary - in my experience, that's what most folks read/care about; we only need to dig into the actual spec if there are questions about details or if we're attempting to enforce the spec, like [probot](https://github.com/probot/semantic-pull-requests) does.

If anything, I think the summary should be simplified further, not removed. The main thing everyday developers need to know are the **feat:** or **fix:** prefixes and the **BREAKING CHANGE:** explanation. The next most important part is when to apply these conventions, which, when using GitHub-flow, is only when squashing and merging PRs, but that is perhaps beyond the scope of the spec.

**Comment by nexdrew** [comment]
I would argue that, when I go to the conventionalcommits.org site, the primary goal should be to quickly and concisely tell **what** the spec is and **why** it's useful, perhaps pointing to a handful of the tools that make developers lives easier when using it. IMO this is what the summary should represent. All the other details can be explained subsequently and secondarily.

**Comment by zkat** [comment]
I'd much rather read as concise a spec as possible, and only read the details if I need to implement something myself.

**Comment by hutson** [comment]
@bcoe @nexdrew @zkat thank you all for your input, and insight, on how you, among many others, use the _Summary_ section to help build a culture that leads to high quality commit messages, and successful product execution. 

@damianopetrungaro I still feel there are opportunities for targeted improvements to the _Summary_ section that may provide additional clarity. Please let me close this issue out and attempt to open up issues that address specific points of confusion I have with the summary that are more targeted and respect the strong value a summary provides.
