### ISSUE TITLE
Capitalisation in examples

### ISSUE THREAD

**Issue by robcresswell** [conventional-commits/conventionalcommits.org#83]
This is minor I suppose, but shouldn't the examples use capitals after the `:`? Given that text is parsed into a `CHANGELOG` and each commit title is supposed to be a standalone sentence, would it make sense to capitalise the first letter of each explanation? 

For example, instead of:

```
feat: allow provided config object to extend other configs
```

use:

```
feat: Allow provided config object to extend other configs
```

Then the generated changelogs would use proper grammar, I think?

**Comment by damianopetrungaro** [comment]
@robcresswell  thank you for opening the issue!

We just merged a PR about capitalization in the commit type.

I agree with your idea, but think that this should not care about it, because the changelogs tools may do it on the fly while generating it.

We may change #82 to be more generic maybe.

wdyt about it?

**Comment by robcresswell** [comment]
Ah that's sensible reasoning, to not be opinionated about casing at this level of the spec and leave it up to parsers. Thanks for the feedback; seems like something I should open in the tools themselves :smiley:

**Comment by dijonkitchen** [comment]
Is there an official parser?

**Comment by Tayflo** [comment]
I understand casing should not be an issue for parser, but still capital after the `:` seems to me common good practice (it's recommanded by [GitHub](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules), [Tim Pope](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), [Chris Beams](https://chris.beams.io/posts/git-commit/#capitalize)).

Since the [Conventional Commits page](https://www.conventionalcommits.org) is a reference for people looking to write tidy commits, using capitalization in given examples would be better, I think.

**Comment by Tayflo** [comment]
@damianopetrungaro may I draw your attention on this topic again? Considering the three authority sources I referred to in my previous post, un-capitalized examples seem to me... pretty unconventional!

Maybe re-open this issue? If it would be accepted and it could help, I would do a pull request but I'm unsure about the project structure; all files in `content/v1.0.0/` should be modified accordingly, is that it? Also the file in `content/next/` I presume.

**Comment by keikoro** [comment]
> I understand casing should not be an issue for parser, but still capital after the : seems to me common good practice (it's recommended by [GitHub](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules), [Tim Pope](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), [Chris Beams](https://chris.beams.io/posts/git-commit/#capitalize)).

> @damianopetrungaro may I draw your attention on this topic again? Considering the three authority sources I referred to in my previous post, un-capitalized examples seem to me... pretty unconventional!

The examples you linked to recommend **the capitalisation of commit messages/commit subjects**, they don't recommend what you seem to be suggesting, i.e. the capitalisation of some other word that appears later in the sentence.

Conventional commits "naturally" decrease readability because their defaulting to lowercase goes against English orthography, which the recommendation by these often cited older sources is obviously based on. Capitalising whatever comes after the colon would only make matters worse because it'd break orthographic convention a second or even _third time_ within one short sentence.

**Comment by keikoro** [comment]
Sorry, should perhaps have tagged you, @Tayflo. ^

**Comment by Tayflo** [comment]
@keikoro Sorry, I forgot to answer.

For me the tag before the colon is a tag, i.e. a label for a category, and hence not a part of the sentence, which starts right after the colon, usually with a verb describing the action taken.

The colon is here used as a semantic separator, not as it would be in a sentence following proper English grammar. To me it equals something like `[feat] Allow provided config object to extend other configs`, except using the colon is quicker to write, probably neater to read, and use only one character.

Hence, it makes more sense to capitalize the character right after the colon. And it also makes sense to me not to put a dot at the end because it is also a kind of title (in addition to saving another character).
